version: "3.8"

services:
  event-navigation-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    # Uncomment the following lines if you need to mount volumes for development
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    #   - /app/.next
    restart: unless-stopped

  # Development service (optional)
  event-navigation-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    profiles:
      - dev
